# Generated by Django 5.2 on 2025-04-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_verification_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
