# Generated by Django 5.2 on 2025-04-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_verification_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="verification_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
